try {
  nonExistentFunction();
} catch (err) {
  console.log("ğŸ§  Name:", err.name);
  console.log("ğŸ“© Message:", err.message);
  console.log("ğŸ“š Stack Trace:\n", err.stack);
}